packages:
  - apps/*
  - libs/*

autoInstallPeers: true

strictPeerDependencies: false

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - nx
  - prisma
